import React, { useState } from 'react';
import { Leaf, LogIn, UserPlus } from 'lucide-react';
import { login, signup } from '../../services/authApi';

interface Props { onAuthenticated: (user: Awaited<ReturnType<typeof login>>) => void; }

const AuthScreen: React.FC<Props> = ({ onAuthenticated }) => {
  const [mode, setMode] = useState<'login' | 'signup'>('login');
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const user = mode === 'login' ? await login(email, password) : await signup(name, email, password); onAuthenticated(user); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to authenticate'); } finally { setLoading(false); } };
  return <main className="min-h-screen bg-slate-900 text-slate-100 flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md bg-slate-800 border border-slate-700 rounded-xl p-8 space-y-5"><div className="text-center"><Leaf className="mx-auto w-10 h-10 text-green-400" /><h1 className="text-3xl font-bold mt-3">NEEV</h1><p className="text-slate-400 mt-1">Smart plant care</p></div><div className="flex bg-slate-900 rounded-lg p-1"><button type="button" onClick={() => setMode('login')} className={`flex-1 py-2 rounded ${mode === 'login' ? 'bg-green-600 text-white' : 'text-slate-400'}`}><LogIn className="inline w-4 h-4 mr-2" />Sign in</button><button type="button" onClick={() => setMode('signup')} className={`flex-1 py-2 rounded ${mode === 'signup' ? 'bg-green-600 text-white' : 'text-slate-400'}`}><UserPlus className="inline w-4 h-4 mr-2" />Create account</button></div>{mode === 'signup' && <input required value={name} onChange={e => setName(e.target.value)} placeholder="Full name" className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 outline-none focus:border-green-500" />}<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 outline-none focus:border-green-500" /><input required minLength={8} maxLength={128} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password (8-128 characters)" className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 outline-none focus:border-green-500" />{error && <p className="text-red-400 text-sm">{error}</p>}<button disabled={loading} className="w-full bg-green-600 hover:bg-green-500 disabled:opacity-50 rounded-lg py-3 font-semibold">{loading ? 'Please wait...' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form></main>;
};
export default AuthScreen;
